### ISSUE TITLE
Secrets in docker compose for default admin and secret key?

### ISSUE THREAD

**Issue by Thalley** [thespad/docker-planka#8]
I want to use [docker secrets](https://docs.docker.com/compose/use-secrets/) in my docker compose file for the following values
```
SECRET_KEY
DEFAULT_ADMIN_USERNAME
DEFAULT_ADMIN_PASSWORD
DEFAULT_ADMIN_EMAIL
DEFAULT_ADMIN_NAME
```

Just doing 
```
      SECRET_KEY: /run/secrets/planka_secret_key
      DEFAULT_ADMIN_USERNAME: /run/secrets/planka_admin_username
      DEFAULT_ADMIN_PASSWORD: /run/secrets/planka_admin_pass
      DEFAULT_ADMIN_EMAIL: /run/secrets/planka_admin_email
      DEFAULT_ADMIN_NAME: /run/secrets/planka_admin_name
```
obviously doesn't work, as the secrets are files and this way they will just be treated as literal strings by planka. 

Per https://github.com/thespad/docker-planka?tab=readme-ov-file#environment-variables-from-files-docker-secrets it is mentioned that environmental values can be prepended with `FILE__` to use them with docker secrets, but that seemingly doesn't work (at least not for docker compose). If I do 
```
      FILE__SECRET_KEY: /run/secrets/planka_secret_key
      FILE__DEFAULT_ADMIN_USERNAME: /run/secrets/planka_admin_username
      FILE__DEFAULT_ADMIN_PASSWORD: /run/secrets/planka_admin_pass
      FILE__DEFAULT_ADMIN_EMAIL: /run/secrets/planka_admin_email
      FILE__DEFAULT_ADMIN_NAME: /run/secrets/planka_admin_name
```

then I am being told that the password in the database is `null`. 

Am I missing something, or is docker secrets with docker compose for this image not supported?

**Comment by thespad** [comment]
The container log should provide output on startup confirming if envs have been set from a secret or not; but not what it's been set *to* (for obvious reasons).

Make sure your secrets are being created correctly; 99 times out of 100 when people run into issues it's because the secret file has an unintended trailing newline as almost every method of creating the files will add one.

Docker recommends using `printf`, you can also use `echo -n` to a similar effect.

**Comment by Thalley** [comment]
Thanks for the quick reply @thespad 

The problem is (not yet anyways) the content of the secrets. With e.g. `DEFAULT_ADMIN_PASSWORD: /run/secrets/planka_admin_pass` the password literally becomes "/run/secrets/planka_admin_pass", and with `FILE__DEFAULT_ADMIN_PASSWORD: /run/secrets/planka_admin_pass` the service complained about missing password. For the latter, I have verified that the file does not contain anything but the password (verified by putting in "test" and seeing a file size of 4 bytes). 

I'll try to output the contents of `FILE__DEFAULT_ADMIN_PASSWORD` later. 

Just to make sure, it's supposed to be `FILE__` with 2 underscores, right? I know the convention that most images use is appending `_FILE` (which I've also tried) with a single underscore.

**Comment by thespad** [comment]
Correct, it's a prefix with two underscores; the baseimage I'm using predates most of the now "standard" images using the `_FILE` suffix convention.

The container logs should show something like this at the start:
```
secret-test  | [migrations] started
secret-test  | [migrations] no migrations found
secret-test  | [env-init] PASSWORD set from FILE__PASSWORD
secret-test  | [env-init] Your secret: FILE__USERNAME
secret-test  |            contains a trailing newline and may not work as expected
secret-test  | [env-init] USERNAME set from FILE__USERNAME
secret-test  | ───────────────────────────────────────
```

**Comment by Thalley** [comment]
Sorry for not getting back to you sooner. I just tried with `FILE__` on a clean install, and it works as expected. Presumably something else went wrong in my first attempt(s) at this, but it seems to work as intended.
